---
title: "Proyecto en R"
output: html_notebook
---

1.Conociendo los datos


```{r}

library(tidyverse)
yearly <- read_csv('C:/Users/edcan/Documents/maestria 2021/segundo semestre/scripting/Proyecto scripting/deaths_handwashing.csv')

View(yearly)
print(yearly)

```

2.El alarmante número de muertes
```{r}
yearly <-yearly %>%
   mutate(proportion_deaths=deaths/births)

view(yearly)
print(yearly)

```

3.Muerte en las clínicas

```{r}
ggplot(yearly,aes(x=year, y=proportion_deaths , color=clinic))+geom_line()

```

4.Comienza el lavado de manos

```{r}
monthly <- read_csv('C:/Users/edcan/Documents/maestria 2021/segundo semestre/scripting/Proyecto scripting/deaths_clinic_1.csv')

monthly <-monthly %>%
   mutate(proportion_deaths=deaths/births)

view(monthly)
print(monthly)

head(monthly)
head(monthly, n=2)

```

5.El efecto del lavado de manos

```{r}

ggplot(monthly,aes(x=date, y=proportion_deaths ,color=proportion_deaths ))+geom_line()+ labs(title = "El efecto del lavado de manos", subtitle = "Graficos")+ labs(x = "Columnas por años") + labs(caption = "(Información basada en la clinica 1)")+labs(y = "Proporcion por muertes")+ labs(colour = "Muertes")



```
6.Los resultados del lavado de manos
```{r}

monthly <-monthly %>%
   mutate(handwashing_started=date)

monthly <-monthly %>%
   mutate(handwashing_started=(date>='1847-01-01'))


ggplot(monthly,aes(x=date, y=proportion_deaths ,color=handwashing_started ))+geom_line()+ labs(title = "El efecto del lavado de manos a partir de 1847", subtitle = "Un antes y un despues del labado demanos")+ labs(x = "Columnas por años") + labs(caption = "(Información basada en la clinica 1)")+labs(y = "Proporcion por muertes")+ labs(colour = "Muertes")


```

7.¿Más lavado de manos, menos muertes?

```{r}
print(monthly)

month_summary<-monthly %>% group_by(handwashing_started) %>%
   summarize(mean_proportion_deaths=mean(deaths, na.rm = TRUE))


print(month_summary)


```

